version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: drupal_db
      MYSQL_USER: drupal_user
      MYSQL_PASSWORD: drupal_pass
    restart: always
    networks:
      - drupal-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: test
      PMA_ARBITRARY: 1
    networks:
      - drupal-network

  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./drupal-website:/var/www/html
    depends_on:
      - db
    networks:
      - drupal-network

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./drupal-website:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - drupal
    networks:
      - drupal-network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - drupal-network

networks:
  drupal-network:
    driver: bridge