sync:
  mutagen:
    alpha: "../../"
    beta: "docker://vactory_mutagen/var/www/html"
    mode: "two-way-resolved"
    configurationBeta:
      permissions:
        defaultFileMode: 644
        defaultDirectoryMode: 755
        defaultOwner: nobody
        defaultGroup: nobody
