display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
  nodes_list:
    display_options:
      fields:
        nid:
          separator: ', '
        title:
          label: Titre
          separator: ', '
        total_score:
          label: Score
          suffix: '%'
        no_count:
          label: Négation
        count:
          label: Total
        langcode:
          label: Language
          separator: ', '
        edit_node:
          text: modifier
      filters:
        langcode:
          expose:
            label: Language
  nodes_score:
    display_options:
      arguments:
        nid:
          exception:
            title: All
      fields:
        id:
          label: 'Identifiant (ID)'
        feedback_type:
          label: Type
        feedback_message:
          label: Message
        langcode_2:
          label: Language
        created:
          label: Créé
        id_1:
          alter:
            text: supprimer
            alt: supprimer
