display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          text_input_required: 'Select any filter and click on Apply to see results'
          bef:
            general:
              secondary_label: 'Advanced options'
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        title:
          separator: ', '
  site_academy_agence_listing:
    display_title: Page
