display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          sort_asc_label: Asc
          sort_desc_label: Desc
      fields:
        title:
          separator: ', '
  block_related_reports:
    display_options:
      arguments:
        field_ar_thematic_target_id:
          exception:
            title: All
  digital_report_listing_page:
    display_title: Page
    display_options:
      arguments:
        name:
          exception:
            title: All
