label: Glossary
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
          text_input_required: 'Select any filter and click on Apply to see results'
          bef:
            general:
              secondary_label: 'Advanced options'
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: ‹‹
            next: ››
      fields:
        title:
          separator: ', '
        body:
          separator: ', '
      title: Glossary
      empty:
        area:
          content:
            value: 'Aucun résultat n''a été trouvé !'
      arguments:
        title:
          exception:
            title: All
  attachment:
    display_title: Attachment
    display_options:
      arguments:
        title:
          exception:
            title: All
  page_1:
    display_title: Page
    display_options:
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      arguments:
        title:
          exception:
            title: All
