display:
  default:
    display_options:
      fields:
        changed:
          separator: ', '
          label: 'Date de modification'
        created:
          separator: ', '
          label: Créé
        fid:
          label: 'Identifiant (FID)'
        filename:
          label: Nom
        type:
          label: Type
        filemime:
          label: 'Type MIME'
        filesize:
          label: Taille
        status:
          label: État
        count:
          label: 'Utilisé dans'
        operations:
          label: Actions
      exposed_form:
        options:
          submit_button: Filtrer
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: "‹\_précédent"
            next: "suivant\_›"
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      filters:
        filename:
          expose:
            label: 'Nom du fichier'
        status:
          expose:
            label: État
        type:
          expose:
            label: Type
      title: Fichiers
      empty:
        area_text_custom:
          content: 'Aucun fichier disponible.'
    display_title: Master
  overview:
    display_title: 'Vue d''ensemble des fichiers'
    display_options:
      menu:
        title: Fichiers
  usage:
    display_title: 'Utilisation du fichier'
    display_options:
      pager:
        options:
          tags:
            previous: "‹\_précédent"
            next: "suivant\_›"
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        entity_label:
          label: Entité
        type:
          label: 'Type d''entité'
        module:
          label: 'Enregistrement du module'
        count:
          label: 'Nombre d''utilisations'
      title: 'Utilisation du fichier'
      arguments:
        fid:
          exception:
            title: All
          title: 'Information d''utilisation du fichier {{ arguments.fid }}'
      menu:
        title: Utilisation
description: 'Trouver et gérer les fichiers.'
