label: Forums
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
          text_input_required: 'Select any filter and click on Apply to see results'
          bef:
            general:
              secondary_label: 'Advanced options'
      fields:
        comment_count:
          label: Contributions
        last_comment_name:
          label: 'Dernière contribution'
        field_vactory_forum_room:
          separator: ', '
      filters:
        field_vactory_date_value:
          expose:
            label: Date
      title: Forums
  page_forum_table:
    display_options:
      fields:
        field_vactory_forum_room:
          separator: ', '
        title:
          label: Titre
          separator: ', '
        field_vactory_forum_status:
          label: État
          separator: ', '
        field_vactory_forums_thematic:
          separator: ', '
        comment_count:
          label: Réponses
        last_comment_name:
          label: 'Dernière réponse'
        last_comment_timestamp:
          label: 'Heure du dernier commentaire'
