display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      fields:
        user_id:
          label: Utilisateur
          separator: ', '
        value:
          separator: ', '
        timestamp:
          label: Date
          separator: ', '
      arguments:
        entity_id:
          exception:
            title: All
        entity_type:
          exception:
            title: All
  results_block:
    display_title: Bloc
  summary_block:
    display_title: Bloc
    display_options:
      fields:
        value_1:
          separator: ', '
        value:
          label: Total
