display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
          bef:
            general:
              secondary_label: 'Advanced options'
      pager:
        options:
          tags:
            previous: ‹
            next: ›
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        created:
          separator: ', '
        title:
          separator: ', '
        node_summary:
          separator: ', '
        field_vactory_image:
          separator: ', '
        field_vactory_date:
          separator: ', '
  global:
    display_title: Page
