display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          sort_asc_label: Asc
          sort_desc_label: Desc
          text_input_required: 'Select any filter and click on Apply to see results'
          bef:
            general:
              secondary_label: 'Advanced options'
            sort:
              advanced:
                collapsible_label: 'Options de tri'
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: ‹‹
            next: ››
      fields:
        title:
          separator: ', '
      empty:
        area_text_custom:
          content: 'Aucun résultat n''a été trouvé !'
  block_masonry:
    display_options:
      block_category: Évènements
  block_slider_large:
    display_options:
      block_category: Évènements
  block_slider_small:
    display_options:
      block_category: Évènements
  block_three_columns:
    display_options:
      block_category: Évènements
  block_two_columns:
    display_options:
      block_category: Évènements
  listing_masonry:
    display_options:
      use_more_text: more
  listing_one_column:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          sort_asc_label: Asc
          sort_desc_label: Desc
          bef:
            sort:
              advanced:
                collapsible_label: 'Options de tri'
      use_more_text: more
  listing_three_columns:
    display_options:
      use_more_text: more
  listing_two_columns:
    display_options:
      use_more_text: more
