label: Fichiers
description: 'Trouver et gérer les fichiers.'
display:
  default:
    display_title: 'Par défaut'
    display_options:
      title: Fichiers
      fields:
        fid:
          label: 'Identifiant (FID)'
        filename:
          label: Nom
          separator: ', '
        filemime:
          label: 'Type MIME'
        filesize:
          label: Taille
        status:
          label: État
          settings:
            format_custom_false: Temporaire
            format_custom_true: Permanent
        created:
          label: 'Date de transfert'
        changed:
          label: 'Date de modification'
        count:
          label: 'Utilisé dans'
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      exposed_form:
        options:
          submit_button: Filtrer
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      empty:
        area_text_custom:
          content: 'Aucun fichier disponible.'
      filters:
        filename:
          expose:
            label: 'Nom du fichier'
        filemime:
          expose:
            label: 'Type MIME'
        status:
          expose:
            label: État
  page_1:
    display_title: 'Vue d''ensemble des fichiers'
    display_options:
      menu:
        title: Fichiers
  page_2:
    display_title: 'Utilisation du fichier'
    display_options:
      title: 'Utilisation du fichier'
      fields:
        entity_label:
          label: Entité
        type:
          label: 'Type d''entité'
        module:
          label: 'Enregistrement du module'
        count:
          label: 'Nombre d''utilisations'
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      arguments:
        fid:
          exception:
            title: All
          title: 'Information d''utilisation du fichier {{ arguments.fid }}'
