settings:
  default_submit_button_label: Soumettre
  default_reset_button_label: Reset
  default_delete_button_label: Delete
  default_preview_next_button_label: Aperçu
  default_preview_label: Aperçu
  dialog_options:
    narrow:
      title: Étroit
    normal:
      title: Normal
    wide:
      title: Large
element:
  default_more_title: Plus
mail:
  default_from_name: '[site:name]'
