# Defines the schema for hello_world module's configuration.

hello_world.settings:
  type: config_object # Specifies this is a configuration object.
  label: "Hello World settings" # Human-readable label.
  mapping: # Defines the key-value pairs within the config object.
    selected_node_nid:
      type: integer # Specifies the expected data type (an integer for the NID).
      label: "Selected Node ID for block" # Human-readable label for this setting.
