<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Contains hello_world.module.
 */

/**
 * Implements hook_theme().
 */
function hello_world_theme($existing, $type, $theme, $path)
{
  return [
    'hello_world' => [
      'variables' => [
        'name' => 'Bouujemaa', //
        'url' => '',
        'link' => '',
      ],
      'template' => 'hello_world', // Specify the template name (without .html.twig).
    ],
  ];
}

function hello_world_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
  // Target the user login form specifically.
  if ($form_id === 'user_login_form') {
    // Add a simple text field.
    $form['hello_world_extra_field'] = [
      '#type' => 'textfield',
      '#title' => t('Your Favorite Moroccan Dish?'), // Use t() for translation
      '#description' => t('Just adding an extra field for practice!'),
      '#weight' => 100, // Optional: control the field's position
    ];
  }

}

