<?php

use Drupal\Core\Url;
/**
 * @file
 * Contains hello_world.module.
 */

/**
 * Implements hook_theme().
 */
function hello_world_theme($existing, $type, $theme, $path)
{
  return [
    'hello_world' => [
      'variables' => [
        'name' => 'Bouujemaa', //
        'url' => '',
        'link' => '',
      ],
      'template' => 'hello_world', // Specify the template name (without .html.twig).
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for node templates.
 */
/**
 * Implements hook_preprocess_HOOK() for node templates.
 */

