<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_entity_base_field_info_alter().
 *
 * @param \Drupal\Core\Field\BaseFieldDefinition[] $fields
 *   An array of base field definitions.
 * @param \Drupal\Core\Entity\EntityTypeInterface $entity_type
 *   The entity type.
 */
function password_policy_enforcer_entity_base_field_info_alter(array &$fields, EntityTypeInterface $entity_type)
{
  // Only alter the user entity type.
  if ($entity_type->id() === 'user') {
    // Check if the password field exists.
    if (isset($fields['pass'])) {
      // Add the PasswordPolicyConstraint to the password field.
      // Drupal now uses PasswordPolicyConstraint not PasswordPolicy
      // from the Drupal11 version!
      $fields['pass']->addConstraint('Drupal\password_policy\Plugin\Validation\Constraint\PasswordPolicyConstraint');
    }
  }
}
/**
 * Implements hook_entity_base_field_info().
 *
 * @param \Drupal\Core\Entity\EntityTypeInterface $entity_type
 *   The entity type definition.
 *
 * @return \Drupal\Core\Field\BaseFieldDefinition[]
 *   An array of base field definitions.
 */
function password_policy_enforcer_entity_base_field_info(EntityTypeInterface $entity_type)
{
  $fields = [];

  if ($entity_type->id() === 'node') {
    $fields['my_custom_field'] = BaseFieldDefinition::create('string')
      ->setLabel(t('My Custom Field'))
      ->setDescription(t('A custom field added to nodes.'))
      ->setSettings([
        'max_length' => 255,
        'default_value' => '',
        'case_sensitive' => FALSE,
      ])
      ->setDisplayOptions('view', [
        'label' => 'above',
        'type' => 'string',
        'weight' => -4,
      ])
      ->setDisplayOptions('form', [
        'type' => 'string_textfield',
        'weight' => -4,
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);
  }

  return $fields;
}

function password_policy_enforcer_update_10001()
{
  $field_storage_definition = BaseFieldDefinition::create('string')
    ->setLabel(t('Custom field  2'))
    ->setSettings([
      'max_length' => 255,
      'default_value' => '',
      'case_sensitive' => FALSE,
    ])
    ->setDisplayOptions('view', [
      'label' => 'above',
      'type' => 'string',
      'weight' => -4,
    ])
    ->setDisplayOptions('form', [
      'type' => 'string_textfield',
      'weight' => -4,
    ])
    ->setDisplayConfigurable('form', TRUE)
    ->setDisplayConfigurable('view', TRUE);

  \Drupal::entityDefinitionUpdateManager()
    ->installFieldStorageDefinition('my_custom_field_2', 'node', 'password_policy_enforcer', $field_storage_definition);
}
