version: "3.2"
services:
  php:
    container_name: "${PROJECT_NAME}_php"
    env_file: .env.prod
    build:
      context: ./
      dockerfile: .docker/php/Dockerfile-prod
    depends_on:
      - db
      - memcached
      - pma
      - filebrowser
    volumes:
      - public_files_data:/var/www/html/sites/default/files
      - private_files_data:/var/www/html/sites/default/private
      - ftp_files_data:/var/www/ftp
      - backup_db:/var/www/backup
    networks:
      - internal
    labels:
      - "io.portainer.accesscontrol.teams=${PORTAINER_TEAM}"
      - "traefik.enable=true"
      # Backend service.
      - "traefik.http.routers.drupal_${PROJECT_NAME}_http.rule=Host(`backend.${PROJECT_BASE_DOMAIN}`)"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_http.entrypoints=http"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_https.rule=Host(`backend.${PROJECT_BASE_DOMAIN}`)"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_https.entrypoints=https"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_https.tls=true"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_https.tls.certresolver=k8spreprodchallenge"
      # Api service.
      - "traefik.http.routers.drupal_${PROJECT_NAME}_api_http.rule=Host(`api.${PROJECT_BASE_DOMAIN}`)"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_api_http.entrypoints=http"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_api_https.rule=Host(`api.${PROJECT_BASE_DOMAIN}`)"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_api_https.entrypoints=https"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_api_https.tls=true"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_api_https.tls.certresolver=k8spreprodchallenge"
      # Media service.
      - "traefik.http.routers.drupal_${PROJECT_NAME}_media_http.rule=Host(`media.${PROJECT_BASE_DOMAIN}`)"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_media_http.entrypoints=http"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_media_https.rule=Host(`media.${PROJECT_BASE_DOMAIN}`)"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_media_https.entrypoints=https"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_media_https.tls=true"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_media_https.tls.certresolver=k8spreprodchallenge"
      - "traefik.http.middlewares.${PROJECT_NAME}-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.${PROJECT_NAME}-redirectscheme.redirectscheme.permanent=true"
  db:
    build:
      context: ./
      dockerfile: .docker/mysql/Dockerfile
    env_file: .env.prod
    container_name: "${PROJECT_NAME}_db"
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - dbdata:/var/lib/mysql
    labels:
      - "io.portainer.accesscontrol.teams=${PORTAINER_TEAM}"
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    env_file: .env.prod
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      - db
    labels:
      - "io.portainer.accesscontrol.teams=${PORTAINER_TEAM}"
      - "traefik.enable=true"
      - "traefik.http.middlewares.${PROJECT_NAME}_pma_auth.basicauth.users=${BASIC_AUTH}"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_pma_http.rule=Host(`pma.${PROJECT_BASE_DOMAIN}`)"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_pma_http.entrypoints=http"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_pma_http.middlewares=${PROJECT_NAME}_pma_auth@docker"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_pma_https.rule=Host(`pma.${PROJECT_BASE_DOMAIN}`)"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_pma_https.entrypoints=https"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_pma_https.tls=true"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_pma_https.middlewares=${PROJECT_NAME}_pma_auth@docker"
  memcached:
    container_name: "${PROJECT_NAME}_memcached"
    image: memcached:1.6.23
    env_file: .env.prod
    command: memcached -m 1024
    restart: unless-stopped
    networks:
      - internal
    labels:
      - "io.portainer.accesscontrol.teams=${PORTAINER_TEAM}"
  filebrowser:
    image: filebrowser/filebrowser
    container_name: "${PROJECT_NAME}_filebrowser"
    env_file: .env.prod
    networks:
      - internal
    volumes:
      - private_files_data:/srv/private
      - public_files_data:/srv/public
      - ftp_files_data:/srv/ftp
      - backup_db:/srv/backup/database
    labels:
      - "io.portainer.accesscontrol.teams=${PORTAINER_TEAM}"
      - "traefik.enable=true"
      - "traefik.http.middlewares.${PROJECT_NAME}_ftp_auth.basicauth.users=${BASIC_AUTH}"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_ftp_http.rule=Host(`ftp.${PROJECT_BASE_DOMAIN}`)"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_ftp_http.entrypoints=http"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_ftp_http.middlewares=${PROJECT_NAME}_ftp_auth@docker"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_ftp_https.rule=Host(`ftp.${PROJECT_BASE_DOMAIN}`)"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_ftp_https.entrypoints=https"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_ftp_https.tls=true"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_ftp_https.tls.certresolver=k8spreprodchallenge"
      - "traefik.http.routers.drupal_${PROJECT_NAME}_ftp_https.middlewares=${PROJECT_NAME}_ftp_auth@docker"
networks:
  internal:
    external: true
volumes:
  dbdata:
  private_files_data:
  public_files_data:
  ftp_files_data:
  backup_db: