version: "3.2"
services:
  php:
    container_name: "${PROJECT_NAME}_php"
    build:
      context: ./
      dockerfile: .docker/php/Dockerfile
    ports:
       - "8080:8080"
    environment:
      IS_DOCKER: "true"
      DOCKER_DB_NAME: "${PROJECT_NAME}_db"
      DOCKER_DB_USER: "${PROJECT_NAME}_user"
      DOCKER_DB_PASSWORD: "123456"
      DOCKER_DB_HOST: "${PROJECT_NAME}_db"
      DOCKER_DB_PORT: "3306"
      FRONTEND_URL: "http://host.docker.internal:3000"
      FRONTEND_CACHE_KEY: "${NEXTJS_CACHE_SECRET}"
    depends_on:
      - db
      - memcached
      - pma
    volumes:
      - ./:/var/www/html
      - ./.docker/php/default.ini:/etc/php81/conf.d/custom.ini:ro
      - ./.docker/nginx/default.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/php/www.conf:/etc/php81/php-fpm.d/www.conf:ro
      - ./.xhprof:/xhprof_output
  db:
    build:
      context: ./
      dockerfile: .docker/mysql/Dockerfile
    container_name: "${PROJECT_NAME}_db"
    environment:
      MYSQL_DATABASE: "${PROJECT_NAME}_db"
      MYSQL_USER: "${PROJECT_NAME}_user"
      MYSQL_PASSWORD: "123456"
    volumes:
      - dbdata:/var/lib/mysql
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    ports:
       - "8085:80"
    environment:
      PMA_HOSTS: "${PROJECT_NAME}_db"
      PMA_USER: "${PROJECT_NAME}_user"
      PMA_PASSWORD: "123456"
      UPLOAD_LIMIT: 2G
      MAX_EXECUTION_TIME: 0
    depends_on:
      - db
  memcached:
    container_name: "${PROJECT_NAME}_memcached"
    image: memcached:1.6.23
    command: memcached -m 1024
  # Utiliser le port 1025 l'or de la configuration swiftmailer.
  mailhog:
    container_name: "${PROJECT_NAME}_mailhog"
    image: mailhog/mailhog:latest
    ports:
      - "8002:8025"
#   # Mutagen
#   mutagen:
#     container_name: "${PROJECT_NAME}_mutagen"
#     build:
#       context: ./
#       dockerfile: .docker/mutagen/Dockerfile
#     init: true
#     volumes:
#       - mutagen:/var/www/html
# volumes:
#   mutagen: {}
volumes:
  dbdata:
