display:
  default:
    display_title: الرئيسي
    display_options:
      exposed_form:
        options:
          submit_button: تطبيق
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
  nodes_list:
    display_options:
      fields:
        title:
          label: العنوان
        total_score:
          label: الدرجة
          suffix: '%'
        count:
          label: المجموع
        langcode:
          label: Language
        edit_node:
          text: تحرير
      filters:
        langcode:
          expose:
            label: Language
  nodes_score:
    display_options:
      arguments:
        nid:
          exception:
            title: الكل
      fields:
        id:
          label: 'المعرف ID'
        feedback_type:
          label: النوع
        feedback_message:
          label: الرسالة
        langcode_2:
          label: Language
        created:
          label: الإنشاء
        id_1:
          alter:
            text: حذف
            alt: حذف
