display:
  default:
    display_title: الرئيسي
    display_options:
      exposed_form:
        options:
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
  block_related_reports:
    display_options:
      arguments:
        field_ar_thematic_target_id:
          exception:
            title: الكل
  digital_report_listing_page:
    display_title: الصفحة
    display_options:
      arguments:
        name:
          exception:
            title: الكل
