display:
  default:
    display_title: الرئيسي
    display_options:
      exposed_form:
        options:
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      fields:
        name:
          label: الوصف
  formation_inscriptions_listing:
    display_title: الصفحة
