label: القاموس
display:
  default:
    display_title: الرئيسي
    display_options:
      exposed_form:
        options:
          submit_button: تطبيق
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
          bef:
            general:
              secondary_label: 'الخيارات المتقدمة'
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
      title: القاموس
      arguments:
        title:
          exception:
            title: الكل
  attachment:
    display_title: المرفق
    display_options:
      arguments:
        title:
          exception:
            title: الكل
  page_1:
    display_title: الصفحة
    display_options:
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
      arguments:
        title:
          exception:
            title: الكل
