label: التعليقات
display:
  default:
    display_title: الافتراضي
    display_options:
      title: التعليقات
      fields:
        comment_bulk_form:
          action_title: Action
        subject:
          label: الموضوع
        name:
          label: المؤلف
        entity_id:
          label: 'نُشِر في'
        changed:
          label: التحديث
        operations:
          label: عمليات
      pager:
        options:
          tags:
            next: 'التالية ›'
            previous: '‹ السابقة'
            first: '« الأولى'
            last: 'الأخيرة »'
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
      exposed_form:
        options:
          submit_button: انتقاء
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      empty:
        area_text_custom:
          content: 'لا تعليقات.'
      filters:
        subject:
          expose:
            label: الموضوع
        langcode:
          expose:
            label: Language
      use_more_text: المزيد
  page_published:
    display_title: 'تعليقات منشورة'
    display_options:
      menu:
        title: التعليقات
  page_unapproved:
    display_title: 'التعليقات الغير موافق عليها'
    display_options:
      fields:
        comment_bulk_form:
          action_title: Action
        subject:
          label: الموضوع
        name:
          label: المؤلف
        entity_id:
          label: 'نُشِر في'
        changed:
          label: التحديث
        operations:
          label: عمليات
      filters:
        subject:
          expose:
            label: الموضوع
        langcode:
          expose:
            label: Language
      menu:
        title: 'التعليقات الغير موافق عليها'
