display:
  default:
    display_title: الرئيسي
    display_options:
      exposed_form:
        options:
          submit_button: تطبيق
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      fields:
        user_id:
          label: المستخدم
        timestamp:
          label: التاريخ
      arguments:
        entity_id:
          exception:
            title: الكل
        entity_type:
          exception:
            title: الكل
  results_block:
    display_title: الصندوق
  summary_block:
    display_title: الصندوق
    display_options:
      fields:
        value:
          label: المجموع
