display:
  default:
    display_title: الرئيسي
    display_options:
      exposed_form:
        options:
          submit_button: تطبيق
          reset_button_label: 'إعادة الضبط'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
          bef:
            general:
              secondary_label: 'الخيارات المتقدمة'
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
  block_masonry:
    display_options:
      block_category: الفعاليات
  block_slider_large:
    display_options:
      block_category: الفعاليات
  block_slider_small:
    display_options:
      block_category: الفعاليات
  block_three_columns:
    display_options:
      block_category: الفعاليات
  block_two_columns:
    display_options:
      block_category: الفعاليات
  listing_masonry:
    display_options:
      use_more_text: المزيد
  listing_one_column:
    display_options:
      exposed_form:
        options:
          submit_button: تطبيق
          reset_button_label: 'إعادة الضبط'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      use_more_text: المزيد
  listing_three_columns:
    display_options:
      use_more_text: المزيد
  listing_two_columns:
    display_options:
      use_more_text: المزيد
