_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  addtoany: 0
  admin_feedback: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  advagg: 0
  advagg_css_minify: 0
  advagg_js_minify: 0
  advagg_mod: 0
  amp: 0
  auto_entityqueue: 0
  automated_cron: 0
  ban: 0
  better_exposed_filters: 0
  block: 0
  block_blacklist: 0
  block_class: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  coffee: 0
  colorapi: 0
  comment: 0
  components: 0
  config: 0
  config_translation: 0
  config_update: 0
  contextual: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dropzonejs: 0
  dynamic_page_cache: 0
  easy_install: 0
  editor: 0
  editor_advanced_link: 0
  email_registration: 0
  entity_reference_revisions: 0
  entityqueue: 0
  faqfield: 0
  features: 0
  field: 0
  field_group: 0
  file: 0
  file_entity: 0
  filter: 0
  flag: 0
  flood_control: 0
  focal_point: 0
  help: 0
  image: 0
  improved_multi_select: 0
  jquery_colorpicker: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  lang_dropdown: 0
  language: 0
  link: 0
  link_target: 0
  linkit: 0
  locale: 0
  login_security: 0
  mailchimp: 0
  mailchimp_campaign: 0
  mailchimp_lists: 0
  mailchimp_signup: 0
  mailsystem: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  media_responsive_thumbnail: 0
  menu_item_extras: 0
  menu_link_attributes: 0
  menu_ui: 0
  merge_translations: 0
  metatag: 0
  metatag_facebook: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_views: 0
  migrate: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  multiple_fields_remove_button: 0
  nocurrent_pass: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_edit: 0
  path: 0
  path_alias: 0
  persistent_login: 0
  rate: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  responsive_image: 0
  responsive_preview: 0
  rest: 0
  scheduler: 0
  search: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_db: 0
  search_api_exclude_entity: 0
  seckit: 0
  serialization: 0
  shortcode: 0
  shortcut: 0
  simplify_menu: 0
  sitemap: 0
  smart_trim: 0
  social_api: 0
  social_auth: 0
  social_auth_facebook: 0
  social_auth_microsoft: 0
  social_media_links: 0
  social_media_links_field: 0
  swiftmailer: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  twig_field_value: 0
  twig_tweak: 0
  ultimate_cron: 0
  update: 0
  upgrade_status: 0
  user: 0
  user_registrationpassword: 0
  vactory_academy: 0
  vactory_academy_agency: 0
  vactory_ads: 0
  vactory_announcements: 0
  vactory_annual_report: 0
  vactory_appbanners: 0
  vactory_appointment: 0
  vactory_banner: 0
  vactory_blog: 0
  vactory_content_access: 0
  vactory_core: 0
  vactory_cross_content: 0
  vactory_datalayer_handler: 0
  vactory_dynamic_field: 0
  vactory_dynamic_field_bootstrap: 0
  vactory_dynamic_field_froala: 0
  vactory_dynamic_field_map: 0
  vactory_dynamic_field_sliders: 0
  vactory_dynamic_field_unitegallery: 0
  vactory_dynamic_field_wysiwyg_templates: 0
  vactory_espace_prive: 0
  vactory_event: 0
  vactory_faq: 0
  vactory_faq_prive: 0
  vactory_field: 0
  vactory_flash_news: 0
  vactory_footer: 0
  vactory_forums: 0
  vactory_frequent_searches: 0
  vactory_glossary: 0
  vactory_google_map_field: 0
  vactory_google_places: 0
  vactory_governance: 0
  vactory_header: 0
  vactory_job_ads: 0
  vactory_jquerycolorpicker_css_fix: 0
  vactory_locator: 0
  vactory_login_token: 0
  vactory_mailchimp: 0
  vactory_mediatheque: 0
  vactory_migrate_ui: 0
  vactory_mur: 0
  vactory_news: 0
  vactory_nextprev: 0
  vactory_notifications: 0
  vactory_otp: 0
  vactory_page: 0
  vactory_paragraphs: 0
  vactory_paragraphs_bg_wrapper: 0
  vactory_partner: 0
  vactory_points: 0
  vactory_press_kit: 0
  vactory_press_release: 0
  vactory_publication: 0
  vactory_publication_prive: 0
  vactory_push_notifications: 0
  vactory_quiz: 0
  vactory_quiz_certificat: 0
  vactory_quiz_history: 0
  vactory_reminder: 0
  vactory_search: 0
  vactory_search_overlay: 0
  vactory_simulation_credit: 0
  vactory_smart_search: 0
  vactory_sms_sender: 0
  vactory_sms_sender_example: 0
  vactory_social_network: 0
  vactory_sondage: 0
  vactory_splashscreen: 0
  vactory_tender: 0
  vactory_testimonials: 0
  vactory_timeout: 0
  vactory_toolbox: 0
  vactory_user: 0
  vactory_user_guide: 0
  vactory_views: 0
  vactory_webform_auto_export: 0
  vactory_webform_custom: 0
  vactory_webform_remote_post: 0
  vactory_webform_satisfaction: 0
  vactory_webform_storage: 0
  vactory_wisepops: 0
  vendor_stream_wrapper: 0
  views_autocomplete_filters: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_infinite_scroll: 0
  viewsreference: 0
  votingapi: 0
  webform: 0
  webform_examples: 0
  webform_jqueryui_buttons: 0
  webform_location_geocomplete: 0
  webform_ui: 0
  workflows: 0
  wysiwyg_template: 0
  wysiwyg_template_core: 0
  yaml_editor: 0
  yoast_seo: 0
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  vactory_starter_kit: 1000
  eu_cookie_compliance: 1001
theme:
  stable: 0
  seven: 0
  vactory: 0
  amptheme: 0
  vactory_amp: 0
  bartik: 0
profile: vactory_starter_kit
