isall: false
url: "node/*/edit\r\n*/node/*/edit\r\n*/node/*/edit*\r\n*/admin/config/system/notifications-configuration\r\n*/node/add/*\r\n*/admin/structure/taxonomy/manage/*/add*\r\n*/taxonomy/term/*/edit*\r\n\r\n*/admin/config/system/vactory-google-places*\n*/admin/config/vactory_points"
selectors: ''
placeholder_text: ''
filtertype: partial
orderable: false
groupresetfilter: false
js_regex: false
buttontext_add: '>'
buttontext_addall: »
buttontext_del: '<'
buttontext_delall: «
buttontext_moveup: 'Move up'
buttontext_movedown: 'Move down'
remove_required_attr: false
