_core:
  default_config_hash: ViXe1Mhsdfc0AY1y-5R7vwxUoVItsnRfbQbQYzQGEEs
api_key: 445229675862f0ade07b8c9d4e29d1cc-us16
api_timeout: 10
cron: false
batch_limit: 100
api_classname: Mailchimp\Mailchimp
test_mode: false
enable_connected: false
connected_id: null
connected_paths: null
webhook_hash: 27e40f7d6151c15a6c5171006f56792d
