_core:
  default_config_hash: OSlQ2kt5a0lrAfT2zNXmTuCSQVBy_0Yyisd4KkNMBpk
use_ajax: false
widget_type: number_up_down
enabled_types_widgets:
  node:
    vactory_academy:
      widget_type: fivestar
      use_ajax: false
bot_minute_threshold: '0'
bot_hour_threshold: '0'
botscout_key: ''
