_core:
  default_config_hash: f4sH8CGbEMFQXKFoGeaHbmIP_f6cOTi02EeFhHSbYyo
langcode: en
page_title: Sitemap
message:
  value: ''
  format: restricted_html
plugins:
  frontpage:
    enabled: true
    weight: -50
    settings:
      title: 'Front page'
      rss: /rss.xml
include_css: true
