_core:
  default_config_hash: 0E8z47ONguVcapiw1PGWDRs6g0NRDCzrym4mP_jcELU
auth:
  social_auth_microsoft:
    route: social_auth_microsoft.redirect_to_microsoft
    img_path: modules/contrib/social_auth_microsoft/img/microsoft_logo.svg
  social_auth_facebook:
    route: social_auth_facebook.redirect_to_fb
    img_path: modules/contrib/social_auth_facebook/img/facebook_logo.svg
post_login: /fr
user_allowed: register
redirect_user_form: false
disable_admin_login: true
disabled_roles:
  administrator: '0'
  super_administrator: '0'
  master: '0'
  webmaster: '0'
  vactory_academy_instructor: '0'
  adviser: '0'
