_core:
  default_config_hash: 7wM8RphD0QT4sFnhmNbn-ouUz0CuyG-PEEDHGRPtxVU
registration: with-pass
registration_ftll_expire: false
registration_ftll_timeout: 86400
notify:
  register_confirmation_with_pass: true
