flash_news_content_type: 0
flash_news_listing_access: 0
flash_news_redirect_to: '404'
vactory_academy_content_type: 0
vactory_academy_listing_access: 0
vactory_academy_redirect_to: '404'
vactory_academy_agency_content_type: 0
vactory_academy_agency_listing_access: 0
vactory_academy_agency_redirect_to: '404'
vactory_annual_report_content_type: 0
vactory_annual_report_listing_access: 0
vactory_annual_report_redirect_to: '404'
vactory_blog_content_type: 1
vactory_blog_listing_access: 0
vactory_blog_redirect_to: '404'
vactory_event_content_type: 0
vactory_event_listing_access: 0
vactory_event_redirect_to: '404'
vactory_faq_content_type: 0
vactory_faq_listing_access: 0
vactory_faq_redirect_to: '404'
vactory_faq_prive_content_type: 0
vactory_faq_prive_listing_access: 0
vactory_faq_prive_redirect_to: '404'
vactory_forum_content_type: 0
vactory_forum_listing_access: 0
vactory_forum_redirect_to: '404'
vactory_glossary_content_type: 0
vactory_glossary_listing_access: 0
vactory_glossary_redirect_to: '404'
vactory_governance_content_type: 0
vactory_governance_listing_access: 0
vactory_governance_redirect_to: '404'
vactory_job_ads_content_type: 0
vactory_job_ads_listing_access: 0
vactory_job_ads_redirect_to: '404'
vactory_news_content_type: 0
vactory_news_listing_access: 0
vactory_news_redirect_to: '404'
vactory_page_content_type: 0
vactory_page_listing_access: 0
vactory_page_redirect_to: '404'
vactory_partner_content_type: 0
vactory_partner_listing_access: 0
vactory_partner_redirect_to: '404'
vactory_press_kit_content_type: 0
vactory_press_kit_listing_access: 0
vactory_press_kit_redirect_to: '404'
vactory_press_release_content_type: 0
vactory_press_release_listing_access: 0
vactory_press_release_redirect_to: '404'
vactory_publication_content_type: 0
vactory_publication_listing_access: 0
vactory_publication_redirect_to: '404'
vactory_publication_prive_content_type: 0
vactory_publication_prive_listing_access: 0
vactory_publication_prive_redirect_to: '404'
vactory_tender_content_type: 0
vactory_tender_listing_access: 0
vactory_tender_redirect_to: '404'
vactory_testimonials_content_type: 0
vactory_testimonials_listing_access: 0
vactory_testimonials_redirect_to: '404'
