_core:
  default_config_hash: FWiXmR6w3RPS-NNBbWG8nsedOa7iNxcKsIoISwnklDs
notification_title: 'SACD : Nouvelle annonce en attente de modération'
notification_message: "Une annonce est en attente d'approbation sur !site_name.<br />\r\nPour la visualiser et la modérer, !link_moderate."
v_notification_title: 'SACD : Votre annonce à été validée'
v_notification_message: "<p>!name,<br />\r\nVotre annonce sur !site_name a été validée. Conformément à votre choix, elle sera visible en ligne pour une durée de !period_validity.<br />\r\nSi vous souhaitez la consulter, !link_annonce.<br />\r\nSi vous souhaitez la supprimer, !link_delete.</p>\r\n"
notification_mail_receiver: {  }
