_core:
  default_config_hash: zWPJ7YH_K2WKZ9tTL1uT_d7ObBIo5w-0v68EC_yU2yk
langcode: en
notifications_default_title: 'New content from [notification:owner_first_name]'
notifications_default_message: 'New content « [notification:content_type:node_title] » of type [notification:content_type] has been added by [notification:owner_first_name] [notification:owner_last_name].'
mail_default_subject: 'New content from [notification:owner_first_name]'
mail_default_message: 'New content « [notification:content_type:node_title] » of type [notification:content_type] has been added by [notification:owner_first_name] [notification:owner_last_name].'
auto_translation: 1
notifications_lifetime: '6'
anonymous_content_types: {  }
authenticated_content_types:
  - vactory_academy
  - vactory_blog
  - vactory_event
  - vactory_news
  - vactory_publication
administrator_content_types:
  - vactory_page
super_administrator_content_types: {  }
master_content_types: {  }
webmaster_content_types: {  }
vactory_academy_instructor_content_types: {  }
adviser_content_types:
  - announcement
  - vactory_academy
mail_active: 0
enable_toast: 1
authenticated_content_types_mail: {  }
administrator_content_types_mail: {  }
super_administrator_content_types_mail: {  }
master_content_types_mail: {  }
webmaster_content_types_mail: {  }
vactory_academy_instructor_content_types_mail: {  }
adviser_content_types_mail: {  }
