_core:
  default_config_hash: hUx977WayHCdbx1Y-89ub4FB4A7wHZ-UmHEOXKLTHe8
langcode: en
from: 'La Factory'
url: 'https://6jj25r.api.infobip.com/sms/2/text/single'
default_sms_body: 'Code OTP '
default_mail_body:
  value: "<p>Code OTP&nbsp;</p>\r\n"
  format: full_html
default_langcode: en
cooldown: '10'
