endpoint: 'https://api.twilio.com/2010-04-01/Accounts/ACac4507c5572532b223b585ca9e3e8d70/Messages.json'
from: Vactory
authorization: basic
api_access_token: ''
api_key_add_to: ''
api_key_query_param_name: ''
api_key_header_prefix: ''
basic_auth_username: ACac4507c5572532b223b585ca9e3e8d70
basic_auth_password: 7752e46d39948bc61e7cb8bc6e5c935f
api_content_type: form_params
data_keys:
  sms_from_key: From
  sms_to_key: To
  sms_body_key: Body
