_core:
  default_config_hash: u2C2386Df7jRD4Ey5I8fp6h3XExg-AMh8DRMA56O4VM
title: 'Test app'
author: VOID
price: FREE
icon: null
app_store_language: us
in_app_store: 'On the App Store'
in_google_play: 'In Google Play'
url: 'https://void.fr/'
button: VIEW
scale: auto
speed_in: 300
speed_out: 400
days_hidden: 15
days_reminder: 90
hide_on_install: true
layer: false
iOS_universal_app: true
append_to_selector: body
android_app_id: com.attijariwafabank.lbankalik
ios_app_id: '1241293206'
admin: false
visibility: exclude
pages: ''
in_amazon_app_store: 'In the Amazon Appstore'
in_windows_store: 'In the Windows Store'
