parallel_correction: '1'
show_quiz_correction: '1'
allow_new_attempts: '1'
validate_answer_title: Valider
allow_new_attempts_title: 'Refaire le quiz'
next_button_title: Continue
_core:
  default_config_hash: kL0QmAnGlOb_DNrgmzsd1m1wgAKAkQW_uGd_hatez3M
