_core:
  default_config_hash: 7eHnmcnd_e5Y46PoOe6hzjDWJ2Sz6Aq8-KrvOpEAgkU
metatag_register_title: ''
metatag_register_description: ''
metatag_login_title: ''
metatag_login_description: ''
path_login: /espace-prive/login
path_register: /espace-prive/register
path_profile: /espace-prive/profile
path_welcome: /espace-prive/welcome
path_password: /espace-prive/password
dependencies:
  enforced:
    module:
      - vactory_espace_prive
