_core:
  default_config_hash: IPpVqeS8xyv9Lu9qKcmZSZYxd7Ond2uzZ0yI1hkD6Qw
notifications:
  increment:
    notification_title: 'New points earned!'
    notification_message: 'You''ve earned @points points by @action_label the page « @entity_title »'
  decrement:
    notification_title: 'Losing points!'
    notification_message: 'You''ve just lost @points points by @action_label the page « @entity_title »'
rules: {  }
dependencies:
  enforced:
    module:
      - vactory_points
